version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # Adjust to the directory where your Dockerfile is located
    schedule:
      interval: "weekly" # Can be daily, weekly, or monthly
    commit-message:
      prefix: "chore" # Customize as needed
    target-branch: "main" # The branch you want updates to be merged into
    rebase-strategy: "auto" # Options: auto, widen, deepen
    open-pull-requests-limit: 5 # Limit the number of open PRs from Dependabot
